name: ridesafe
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.14
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.0
  geolocator: ^10.1.0
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  shared_preferences: ^2.2.0
  geocoding: ^3.0.0
  flutter_map_marker_popup: ^6.0.1
  flutter_map_marker_cluster: ^1.3.0
  flutter_map_location_marker: ^8.0.5
  flutter_map_cancellable_tile_provider: ^2.0.0
  supabase_flutter: ^1.10.25
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/bike.png
    - assets/images/motorcycle.png
  
    
  
    